name: How to manually trigger a workflow

# This describes the event that will trigger the workflow
on: 
    workflow_dispatch:
      inputs:
        username:
          description: 'what is your github username?'
          required: true
        reason:
          description: 'Why are you running this workflow manually?'
          required: false
          default: ""

# This is the workflow/jobs that will be triggered by the events above
jobs:
  tests_manual_workflow:
    runs-on: ubuntu-latest
    env:
      token: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
      issues: write
      actions: write
    steps:
    - run: |
        echo "User ${{ github.event.inputs.username }} ran a workflow manually."
        echo "Because ${{ github.event.inputs.reason }}."
        echo "The workflow was triggered by ${{ github.event.inputs.username}}"
    - run: |
        env
        echo ${token}
    - name: run-ls
      run: |
          pwd
          ls
    - name: checkout
      uses: actions/checkout@v4
      with: 
          token: ${{ env.token }}
    - name: 'check-directory'
      run: |
          pwd
          ls
    - name: Get-Event-Payload
      run: |
          echo "The event payload is:"
          echo "${{ toJson(github.event) }}"
    - name: 'Print-All-Github-Contexts'
      run: |
          echo "The github context is:"
          echo "${{ toJson(github) }}"

