name: How to manually trigger a workflow

# This describes the event that will trigger the workflow
on: 
    workflow_dispatch:
      inputs:
        username:
          description: 'what is your github username?'
          required: true
        reason:
          description: 'Why are you running this workflow manually?'
          required: false
          default: ""

# This is the workflow/jobs that will be triggered by the events above
jobs:
  tests_manual_workflow:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os}}
    env:
      token: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
      issues: write
      actions: write
    steps:
    - run: |
        echo "User ${{ github.event.inputs.username }} ran a workflow manually."
        echo "Because ${{ github.event.inputs.reason }}."
        echo "The workflow was triggered by ${{ github.event.inputs.username}}"

    - name: 'Check OS'
      run: |
          echo "Running on ${{ matrix.os }}"
          echo "The current runner is ${{ runner.os }}"
          
    - run: |
        env
        echo ${token}
    - name: run-ls
      run: |
          pwd
          ls
    - name: checkout
      uses: actions/checkout@v4
      with: 
          token: ${{ env.token }}
    - name: 'check-directory'
      run: |
          pwd
          ls
    - name: Get-Event-Payload
      run: |
          echo "The event payload is:"
          echo "${{ toJson(github.event) }}"
    - name: 'Print-All-Github-Contexts'
      run: |
          echo "The github context is:"
          echo "${{ toJson(github) }}"
    
    - name: Build with logs
      run: |
          mkdir ${{ github.workspace }}/build_logs
          echo "Logs from building" > ${{ github.workspace }}/build_logs/build.logs
          exit 1
    - name: Upload logs on fail
      if: ${{ failure() }}
      uses: actions/upload-artifact@v4
      with:
        name: build_logs
        path: ${{ github.workspace }}/build_logs

