name: Testing workflows

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_workflow:
    runs-on: ubuntu-latest
    if : ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'push' || github.event_name == 'pull_request' }}
    steps:
     - name: Check_context
       run: |
        echo "$GITHHUB_CONTEXT"