name: Testing workflows

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env:
    github_token: ${{ secrets.GITHUB_TOKEN }}
permissions:
    contents: write
    issues: write
    actions: write
    pull-requests: write
    deployments: write
    packages: write
    statuses: write
    checks: write
    pages: write
    
        

jobs:
  test_workflow:
    runs-on: ubuntu-latest
    if : ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'push' || github.event_name == 'pull_request' }}
    steps:
     - name: Check_context
       run: |
        echo "$GITHHUB_CONTEXT" > context.json
       env:
         GITHUB_CONTEXT: ${{ toJson(github) }}
     - name: Upload context
       uses: actions/upload-artifact@v4
       with:
         name: context
         path: ${{ github.workspace }}
     - name: Download context
       uses: actions/download-artifact@v4
       with:
         name: context
         path: ${{ github.workspace }}

     - name: Check_Default_env
       run: |
        file=$(eval env)
        echo "$file" >> env.json

     - name: Upload env
       uses: actions/upload-artifact@v4
       with:
         name: env
         path: ${{ github.workspace }}
     - name: Download env
       uses: actions/download-artifact@v4
       with:
         name: env
         path: ${{ github.workspace }}
         
