name: triggers

on:
    workflow_dispatch:
        inputs:
            homedrive:
                description: 'The home drive on the machine'
                required: false
            logLevel:
                description: 'Log level'
                default: 'warning'
                type: choice
                options:
                - info
                - warning
                - debug
            tag:
                description: 'Apply tag after successfull test run'
                required: true
                type: boolean
            environment:
                    description: 'Environment to run tests against'
                    type: environment
                    required: false
                    default: 'development'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello wrom branch workflow"
      - run: |
            echo "Homedrive: ${{ inputs.homedrive }}"
            echo "Log level: ${{ inputs.logLevel }}"
            echo "Tag source: ${{ inputs.tag }}"
            echo "Environment ${{ github.event.inputs.environment }}"
      
      - name: Functions
        if: contains(github.event.inputs.logLevel, 'info') || contains(github.event.inputs.logLevel, 'debug')
        run: |
            echo "Log level is info or debug"
            echo "Running functions"
  matrix-job:
        strategy:
            fail-fast: false
            max-parallel: 3
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
                node-version: [16, 18, 20]
        runs-on: ${{ matrix.os }}
        steps:
            - name: 'set up node'
              uses: actions/setup-node@v4
              with:
                node-version: ${{ matrix.node-version }}